### ISSUE TITLE
URL woes

### ISSUE THREAD

**Issue by mtsharpe** [dc-wdi-22/seekr-backend#11]
<img width="843" alt="screen shot 2018-05-08 at 10 45 26 am" src="https://user-images.githubusercontent.com/35971325/39764331-6bd16bb8-52ad-11e8-92a8-2b1f83c9a03d.png">
<img width="712" alt="screen shot 2018-05-08 at 10 49 28 am" src="https://user-images.githubusercontent.com/35971325/39764442-9c307420-52ad-11e8-9ce9-1cc681bfee9c.png">
<img width="1051" alt="screen shot 2018-05-08 at 10 49 36 am" src="https://user-images.githubusercontent.com/35971325/39764450-a195282a-52ad-11e8-8ca3-fc3c28411634.png">
<img width="745" alt="screen shot 2018-05-08 at 10 50 00 am" src="https://user-images.githubusercontent.com/35971325/39764461-a74165c2-52ad-11e8-9354-8cd2f2fbbfac.png">

See attached files. Getting the same error in reverse on /jobs link

**Comment by aspittel** [comment]
According to the documentation:

```
lookup_field - The field on the target that should be used for the lookup. Should correspond to a URL keyword argument on the referenced view. Default is 'pk'.
```
I would change id to pk in the urls file!

**Comment by jasonptoups** [comment]
omg thank you!
